### ISSUE TITLE
布局只能能在java里面定义吗

### ISSUE THREAD

**Issue by soyoungboy** [dongjunkun/DropDownMenu#1]
你好，在使用你的DropDownMenu过程中有个疑问，就是下面内容显示区域只能在java里面定义，不能再xml布局里面去写吗？

**Comment by dongjunkun** [comment]
暂时不能，后期有时间会优化这个

**Comment by soyoungboy** [comment]
谢谢回答，我试着在java里面写下，感觉这样有点不方便，希望改进，但是这个很有用，在项目里面已经开始用了

**Comment by brucewuu520** [comment]
点击下面的空白处会消失吗？

**Comment by dongjunkun** [comment]
会的
