### ISSUE TITLE
是否支持下拉列表两行或者三行（类点评、美团）扩展

### ISSUE THREAD

**Issue by NicodeLee** [dongjunkun/DropDownMenu#3]

**Comment by dongjunkun** [comment]
支持的，只是没有实现

**Comment by ganghuaChen** [comment]
怎么实现？

**Comment by dongjunkun** [comment]
其中的一个View布局
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="horizontal">

    <ListView
        android:layout_width="0dp"
        android:layout_height="match_parent"
        android:layout_weight="1"/>

    <ListView
        android:layout_width="0dp"
        android:layout_height="match_parent"
        android:layout_weight="1"/>

</LinearLayout>
不限于ListView，GridView，任何自定义的布局都是可以的
