### ISSUE TITLE
我给第二个选项赋值的时候 赋值不上去

### ISSUE THREAD

**Issue by AmbitiousYoung** [dongjunkun/DropDownMenu#31]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference at com.chexiu.widget.dropdownmenu.DropDownMenu.setTabText(DropDownMenu.java:181)

提示setTabText空，但是在listview.setOnItem事件又可以。

**Comment by dongjunkun** [comment]
用在Activity里面还是Fragment里面，可不可以粘贴下源代码

**Comment by AmbitiousYoung** [comment]
已经好了
