### ISSUE TITLE
gradle导入有问题

### ISSUE THREAD

**Issue by RitzoneX** [dongjunkun/DropDownMenu#4]
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2311Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72311Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComGithubDongjunkunDropDownMenu101Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources
/Users/zzz/GitHub/MyApplication22/app/build/intermediates/res/merged/debug/mipmap-hdpi-v4/ic_launcher.png: error: Duplicate file.
/Users/zzz/GitHub/MyApplication22/app/build/intermediates/res/merged/debug/mipmap-hdpi/ic_launcher.png: Original is here. The version qualifier may be implied.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 0.428 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by dongjunkun** [comment]
已经修复
