### ISSUE TITLE
楼主这有问题啊

### ISSUE THREAD

**Issue by aeatho** [dongjunkun/DropDownMenu#5]
要是contentView放置一个fragment,,,,怎么处理？？？？求解决

**Comment by dongjunkun** [comment]
fragment本质还是一个view只是有它自己的生命周期，可以这样用
 <fragment
        android:id="@+id/fragment"
        android:name="com.xxx.MyFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
